### ISSUE TITLE
Make menus dark blue

### ISSUE THREAD

**Issue by ktbarrett** [eddy147/vscode-theme-true-blue#1]
Wondering if you would consider making the bordering menu and file list colors a darker blue rather than dark grey, like is seen in [the blue mood sublime text theme](https://github.com/blue-mood/blue-mood-sublime).

![blue mood sublime text](https://raw.githubusercontent.com/blue-mood/blue-mood-everything/master/screenshots/sublime-screenshot.png)

**Comment by eddy147** [comment]
Good suggestion, will do.

**Comment by eddy147** [comment]
@ktbarrett pls see https://marketplace.visualstudio.com/items?itemName=eddy1470669.blue
hope this is what you wanted

**Comment by ktbarrett** [comment]
Looks good, thanks!
